<?php
 function cipher_menu(){
   $items = array();
   $items['cipher'] = array(
     'title' => "cipher",
     'type' => MENU_NORMAL_ITEM,
     'access callback' => TRUE,
     'page callback' => 'drupal_get_form',
     'page arguments' => array('cipher_form'),
   );
   $items['cipher_success_page'] = array(
    'title' => "Success",
    'page callback' => 'cipher_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
   return $items;
 }

function cipher_form(){
  $form = array();
  $form['input']= array(
    '#title' => 'Input',
    '#type' => 'textfield',
    '#description' => t('Enter a string'),
    '#required' => TRUE,
  );
  $form['direction']= array(
    '#type' => 'textfield',
    '#description' => t('Enter left or right'),
    '#element_validate' => array('element_validate_direction'),
    '#required' => TRUE,
  );
  $form['amount']= array(
    '#type' => 'textfield',
    '#description' => t('Enter a number'),
    '#element_validate' => array('element_validate_integer_positive','element_validate_range'),
    '#required' => TRUE,

  );
  $form['submit'] = array(
     '#type' => 'submit',
     '#value' => 'Ciph',
   );
  return $form;
  }
function cipher_form_submit($form, &$form_state) {
$clicks = $number = $form_state['values']['amount'];
$input = $form_state['values']['input'];
$direction = $form_state['values']['direction'];
$output = "";
$str_len = strlen($input);
 for($i=0;$i<$str_len;$i++) {
   $cur_char = ord(substr($input,$i,1));
   if(($cur_char > 64 && $cur_char < 91)&&($direction === 'right')) {
        $cur_char = $cur_char - 65;
        $cur_char = ($cur_char + $clicks)%26 + 65;
    } elseif (($cur_char > 96 && $cur_char < 123)&&($direction ==='right')) {
        $cur_char = $cur_char - 97;
        $cur_char = ($cur_char + $clicks)%26 + 97;
    } elseif (($cur_char > 64 && $cur_char < 91)&&($direction === 'left')) {
        $cur_char = $cur_char - 65;
        if($cur_char < 97){
          $cur_char = $cur_char + 25;
        }
        $cur_char = ($cur_char - $clicks)%26 + 65;
    }elseif (($cur_char > 96 && $cur_char < 123)&&($direction ==='left')) {
        $cur_char = $cur_char - 97;
        if($cur_char < 97){
          $cur_char = $cur_char + 25;
        }
        $cur_char = ($cur_char - $clicks)%26 + 97;
    }
     $output .= chr($cur_char);
   }
   $_SESSION['cipher_output'] = $output;
   $form_state['redirect'] = 'cipher_success_page';
}


   function cipher_success(){
     $answer = $_SESSION['cipher_output'];
     return $answer;
   }
   function element_validate_range($element) {
    if ($element['#value'] > 10|| $element['#value'] < 0) {
        form_error($element, t('Number must be less than 10 or greater than 0.'));
    }
}
function element_validate_direction($element) {
 if (($element['#value'] != 'left') && ($element['#value'] != 'right')) {
     form_error($element, t('must be left or right'));
 }
}
